In [2]:
import pickle
from pathlib import Path
import numpy as np
import torch
import pandas as pd
import seaborn as sns

from src.models.net import Net, NetPostClaire, AutoEncoder1D
from src.train import BATCH_SIZE, IMAGE_DIMENSIONS


reminder of what the inputs look like

In [39]:
data_dir = Path("/Users/eddie-odonnell/Desktop/data-science-code/spotify-tagging/data_collection/spectrograms/data/arrays/test_sample_averaged")
npy_files = sorted(data_dir.glob("*.npy"))
training_data = np.array([np.load(f) for f in npy_files])

In [15]:
predictions = pickle.load(open("autoencoder1d_test_results.pkl", "rb"))

In [21]:
predictions[0][-1]

array([[-0.00604606, -0.03035752, -0.06209952, -0.05812822, -0.04446028,
         0.10322045,  0.01377229, -0.21838936,  0.06437944,  0.0394805 ,
         0.16810757,  0.07202139,  0.03047332, -0.09547523, -0.23591119,
        -0.00343021, -0.0620503 , -0.1476298 ,  0.10507394,  0.14898506,
        -0.12233809,  0.1210191 ,  0.10469772,  0.04056011,  0.07086434,
         0.01505531,  0.18904465,  0.03029563, -0.01400569, -0.05796582,
         0.08175082, -0.12388355, -0.01647154, -0.10901405,  0.13890736,
        -0.2847482 ,  0.30183703,  0.03077365, -0.13302934, -0.04106805,
        -0.2310499 , -0.08614889, -0.00802065,  0.17450497, -0.08155634,
        -0.10664655,  0.04684503,  0.18583426,  0.06034072, -0.03920843,
         0.02234396,  0.12033109, -0.16861089, -0.13730249, -0.08966859,
         0.08742737, -0.1021224 ,  0.02088393, -0.04146617, -0.13011864,
         0.1726    , -0.00244578,  0.06906474,  0.2944508 ,  0.20824602,
         0.03268611, -0.15603298, -0.05981319, -0.0

In [19]:
training_data

array([ 0.6169987 , -0.13511929, -1.7969292 , -2.26368   , -1.207496  ,
       -1.0142436 , -1.8657387 , -1.1939573 , -0.51479053, -1.1225924 ,
       -1.6219416 , -0.53813595, -0.10587928, -0.89759064, -1.0286397 ,
       -0.67891794, -0.82579273, -1.5012056 , -1.1849227 , -1.2522132 ,
       -0.771284  , -0.67623943, -1.4842763 , -1.4435748 , -1.2173615 ,
       -0.9500626 , -1.4544417 , -1.173345  , -0.903668  , -1.3574797 ,
       -1.3082671 , -0.9721114 , -1.0449533 , -1.0262758 , -1.1460829 ,
       -1.2523317 , -1.3483857 , -1.0328557 , -0.99040747, -1.30719   ,
       -1.1230862 , -0.7444976 , -0.51361626, -1.1054143 , -1.3338428 ,
       -1.2838317 , -1.1051061 , -1.1702113 , -0.7431204 , -0.9404057 ,
       -1.3107381 , -1.2454631 , -0.688505  , -0.64035547, -1.192082  ,
       -1.201357  , -1.0368184 , -0.7176765 , -0.7322216 , -0.8503073 ,
       -0.8584556 , -0.78351724, -0.859562  , -0.91819805, -0.84380025,
       -0.9011554 , -1.0050173 , -0.87465876, -0.79954183, -0.92

In [62]:
from numpy import random

random_arrays = []
for _ in range(len(training_data)):
    random_array = random.rand(len(training_data[0]))
    random_array = (random_array - random_array.mean()) / random_array.std()
    random_arrays.append(random_array)



In [32]:
from sklearn.metrics.pairwise import cosine_similarity

In [35]:
predictions[0][-1]

array([[-0.00604606, -0.03035752, -0.06209952, -0.05812822, -0.04446028,
         0.10322045,  0.01377229, -0.21838936,  0.06437944,  0.0394805 ,
         0.16810757,  0.07202139,  0.03047332, -0.09547523, -0.23591119,
        -0.00343021, -0.0620503 , -0.1476298 ,  0.10507394,  0.14898506,
        -0.12233809,  0.1210191 ,  0.10469772,  0.04056011,  0.07086434,
         0.01505531,  0.18904465,  0.03029563, -0.01400569, -0.05796582,
         0.08175082, -0.12388355, -0.01647154, -0.10901405,  0.13890736,
        -0.2847482 ,  0.30183703,  0.03077365, -0.13302934, -0.04106805,
        -0.2310499 , -0.08614889, -0.00802065,  0.17450497, -0.08155634,
        -0.10664655,  0.04684503,  0.18583426,  0.06034072, -0.03920843,
         0.02234396,  0.12033109, -0.16861089, -0.13730249, -0.08966859,
         0.08742737, -0.1021224 ,  0.02088393, -0.04146617, -0.13011864,
         0.1726    , -0.00244578,  0.06906474,  0.2944508 ,  0.20824602,
         0.03268611, -0.15603298, -0.05981319, -0.0

In [36]:
cosine_similarity([random_array], predictions[0][-1])

array([[-0.10832768]])

In [43]:
training_data[-1]

array([-1.2047973 , -1.5190822 , -1.141518  , -1.3527972 , -0.14726247,
        0.55674237, -0.66051406,  0.17262867,  0.44949922,  0.0260439 ,
        1.8592076 ,  1.5663177 , -0.76798236, -0.02837382,  0.06950754,
       -0.0135157 ,  1.1123387 ,  0.09691539, -0.7742378 , -1.2447573 ,
       -1.4163802 , -0.22140452,  0.37849912, -1.3695108 , -1.6069412 ,
       -1.3790418 , -1.6104518 , -0.90690863, -0.58915794, -0.83463115,
       -0.9008977 , -1.3814709 , -1.1876664 , -0.01701351, -0.53629553,
       -1.4454463 , -1.4736015 , -1.047634  , -1.0417229 , -1.4278324 ,
       -1.4499054 , -1.1137911 , -0.9494623 , -0.2771497 ,  0.28599322,
       -0.71202374, -1.3255076 , -1.3187397 , -0.913388  , -0.9890619 ,
       -1.2029548 , -1.1798319 , -0.32604644, -0.28518355, -1.0665126 ,
       -1.015654  , -1.1429188 , -1.1279297 , -1.1508136 , -0.4787452 ,
       -0.85230315, -1.1994498 , -1.1876447 , -0.9869391 , -0.98753786,
       -1.095354  , -1.0936251 , -0.9631953 , -0.8629089 , -0.66

In [54]:
cosine_similarity(training_data, [p[-1][0] for p in predictions]).mean()

0.0065410356

In [65]:
cosine_similarity(training_data, random_arrays).mean()

-0.0003766708999233814

OK SO AT LEAST IT IS AN ORDER OF MAGNITUDE BETTER THAN RANDOM THANK THE LORD. Still pretty awful though

In [23]:
# look at the weights...???

In [3]:
model_path = "../data_collection/spectrograms/models/2025_10_30_AutoEncoder1D_1.pickle"

INPUT_SIZE = 128
LATENT_SIZE = 8
model = AutoEncoder1D(input_size=INPUT_SIZE, latent_size=LATENT_SIZE)
model.load_state_dict(torch.load(model_path))

<All keys matched successfully>

In [4]:
model.state_dict()

OrderedDict([('encoder.0.weight',
              tensor([[[-0.5091,  0.2488, -0.2846]],
              
                      [[-0.5477, -0.2875, -0.0145]],
              
                      [[-0.3858,  0.1329,  0.4879]],
              
                      [[-0.0296, -0.0867, -0.4876]],
              
                      [[ 0.0535, -0.5098,  0.4069]],
              
                      [[ 0.1072, -0.4119, -0.0141]],
              
                      [[-0.3830, -0.4233,  0.4432]],
              
                      [[ 0.0194, -0.0785,  0.2986]],
              
                      [[ 0.1192,  0.3665, -0.4530]],
              
                      [[ 0.3475,  0.1479, -0.3504]],
              
                      [[ 0.4985, -0.2887,  0.0967]],
              
                      [[ 0.4645,  0.5649,  0.0783]],
              
                      [[ 0.5104, -0.5697,  0.2083]],
              
                      [[ 0.1747,  0.4056, -0.1385]],
              
              